name: dslink_js
version: 1.0.0
description: DSLink SDK for Dart
dependencies:
  yaml: "^2.1.2"
  calzone: ">=0.2.1"
    # path: ../calzone.dart
  grinder: any
  dslink:
    path: ./temp/sdk-dslink-dart
